---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgBcYmynsE8DlF/d7/u9jaHRY7xxsXnEcHblx/8TZBbSQ6T4C4P/hMLiXHDnKe55N9iQE9lzX8wnf+GNk45dgnW9Ek0tlXco/s/sANu+Yn/r1VGXpeBegmfKFM6xHPZ9cojANzVTOoe6P9ei8iA8YdWN2QhPu0721eMAh8G6ySCR+khKKfQ3P806yNODXgahl0TtNRT+vNz+iH3tW7S6s04C0iIeuGoWD4RZhHpTvdoJ90WbsPr5abNqDO9GkDOIOy1xdYR06ROWSrC4FAwoT2beQsNpHTSSyPLTLtK33tsUaf/MjeXWm8GxerGWU3gjYkUFbrKEBCqWu0WBlBOy19j0jxpKoHVNdky/RcUKM1rzI4pRBZdu+lr7O5lBf8t6x6c4I3RogsYFP9GR0MXdRWRBSaSF8jaV2xng/HO29mX/sxQXN/l/XiKWf97WlgrX1EC6F5nLDJQLx5drPf34f09lJdYwkK9JcILHOufJCb30nikH14II2RZ/nLEFjS1ZDl010aU2kDJYHave4tOfnBQyTK45RP2QHfUigx5W3A5ts3AWHBiA6pHZJb8GF4CURUUyMbGTheIl6jx4HWqdHl9eNwX2GaeFHRtGCrIRcaCaf/KHJExIdArjzv+z+ubIndBaPW3BVGKlPm7niD+OYnG3ud9giLCM6oeNylJkzPgVS/fxaEcWyow5ZRGi+vYadlDXZpvTOBmFYHBaGCBYjTyRW+juDFSw97SwEZLnc2GQDM/3Y8XSVjqhZKcD6Zm5BGXz9nVQQybjm8LkNeULgr4QDAiHz40074CmfDWVQOJ1ahE=
  template:
    metadata:
      name: alertmanager-slack-secret
      namespace: monitoring
    type: Opaque
